# Generated by Django 5.0.1 on 2024-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Player nickname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Player email')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Player password hash')),
                ('reg_date', models.DateTimeField(verbose_name='Player registation date')),
                ('ip_address', models.CharField(max_length=255, verbose_name='Player IP Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Player phone')),
                ('freecoin', models.IntegerField(verbose_name='Player freecoin balance')),
                ('goldcoin', models.IntegerField(verbose_name='Player goldcoin balance')),
                ('bonuscoin', models.IntegerField(verbose_name='Player bonuscoin balance')),
                ('trashcoin', models.IntegerField(verbose_name='Player bonuscoin balance')),
                ('active_table', models.IntegerField(verbose_name='Player active table')),
                ('reputation', models.IntegerField(verbose_name='Player reputation')),
                ('rating', models.IntegerField(verbose_name='Player rating')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Player wallet address')),
                ('django_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Player Django username')),
                ('google_uid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Player google account ID')),
                ('online_mail', models.BooleanField(verbose_name='Player online by email')),
                ('online_google', models.BooleanField(verbose_name='Player online by Google')),
                ('online_metamask', models.BooleanField(verbose_name='Player online by Metamask')),
                ('email_is_verified', models.BooleanField(verbose_name='Email address is verified')),
                ('referer_id', models.IntegerField(blank=True, null=True, verbose_name='Referer user ID')),
                ('referal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Personnel referal code')),
            ],
        ),
    ]
