# Generated by Django 5.0.1 on 2024-01-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='trashcoin',
            field=models.IntegerField(verbose_name='Player trashcoin balance'),
        ),
    ]
