# Generated by Django 5.0.1 on 2024-02-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_players_trashcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='last_activity',
            field=models.IntegerField(default=0, verbose_name='Player last activity'),
            preserve_default=False,
        ),
    ]
