# Generated by Django 5.0.1 on 2024-02-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_players_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='coin_activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
