# Generated by Django 5.0.1 on 2024-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_players_coin_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='freegamehistory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='goldgamehistory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='trashgamehistory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
