# Generated by Django 5.0.1 on 2024-02-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_players_freegamehistory_players_goldgamehistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='trashcoin',
            new_name='democoin',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='freecoin',
            new_name='silvercoin',
        ),
        migrations.AddField(
            model_name='players',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
