# Generated by Django 5.0.1 on 2024-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_rename_trashcoin_players_democoin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Player phone'),
        ),
        migrations.AddField(
            model_name='players',
            name='phone_is_verified',
            field=models.BooleanField(default=0, verbose_name='Email address is verified'),
            preserve_default=False,
        ),
    ]
