# Generated by Django 5.0.1 on 2024-02-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_players_country_players_phone_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='freegamehistory',
            new_name='demogamehistory',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='trashgamehistory',
            new_name='silvergamehistory',
        ),
    ]
