# Generated by Django 5.0.1 on 2024-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_rename_freegamehistory_players_demogamehistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='country',
            field=models.IntegerField(blank=True, null=True, verbose_name='Player country'),
        ),
        migrations.AlterField(
            model_name='players',
            name='phone_is_verified',
            field=models.BooleanField(verbose_name='Phone is verified'),
        ),
    ]
