# Generated by Django 5.0.1 on 2024-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_players_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Player ID number')),
                ('coin_activity', models.TextField(blank=True, null=True)),
                ('silvergamehistory', models.TextField(blank=True, null=True)),
                ('goldgamehistory', models.TextField(blank=True, null=True)),
                ('demogamehistory', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='players',
            name='coin_activity',
        ),
        migrations.RemoveField(
            model_name='players',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='players',
            name='demogamehistory',
        ),
        migrations.RemoveField(
            model_name='players',
            name='goldgamehistory',
        ),
        migrations.RemoveField(
            model_name='players',
            name='silvergamehistory',
        ),
    ]
