# Generated by Django 5.0.1 on 2024-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_playersdata_remove_players_coin_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersdata',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='Player ID number'),
        ),
    ]
