# Generated by Django 5.0.1 on 2024-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_playersdata_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='language',
            field=models.IntegerField(default=1, verbose_name='Player language'),
        ),
        migrations.AddField(
            model_name='playersdata',
            name='bonusgamehistory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
