# Generated by Django 5.0.1 on 2024-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_players_language_playersdata_bonusgamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='democoin',
            field=models.IntegerField(verbose_name='Player democoin balance'),
        ),
        migrations.AlterField(
            model_name='players',
            name='silvercoin',
            field=models.IntegerField(verbose_name='Player silver balance'),
        ),
    ]
