# Generated by Django 5.0.1 on 2024-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_players_democoin_alter_players_silvercoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='sid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Socket SID'),
        ),
    ]
