# Generated by Django 5.0.1 on 2024-04-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_players_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersdata',
            name='bonusgamehistory',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playersdata',
            name='coin_activity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playersdata',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playersdata',
            name='demogamehistory',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playersdata',
            name='goldgamehistory',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playersdata',
            name='silvergamehistory',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
