# Generated by Django 5.0.1 on 2024-04-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_playersdata_bonusgamehistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playersdata',
            name='comments',
        ),
    ]
