# Generated by Django 5.0.1 on 2024-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_remove_playersdata_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersdata',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
