# Generated by Django 5.0.1 on 2024-04-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_playersdata_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='referal_code',
        ),
    ]
