# Generated by Django 5.0.1 on 2024-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_remove_players_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='referal_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Personnel referal code'),
        ),
    ]
