# Generated by Django 5.0.1 on 2024-04-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0019_players_referal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='playersdata',
            old_name='demogamehistory',
            new_name='history_bonus',
        ),
        migrations.RenameField(
            model_name='playersdata',
            old_name='goldgamehistory',
            new_name='history_gold',
        ),
        migrations.RenameField(
            model_name='playersdata',
            old_name='silvergamehistory',
            new_name='history_silver',
        ),
        migrations.AddField(
            model_name='playersdata',
            name='airdrop_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersdata',
            name='airdrop_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersdata',
            name='airdrop_silver',
            field=models.IntegerField(default=0),
        ),
    ]
