# Generated by Django 5.0.1 on 2024-04-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_mailserversettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersdata',
            name='ref_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersdata',
            name='ref_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playersdata',
            name='ref_silver',
            field=models.IntegerField(default=0),
        ),
    ]
