# Generated by Django 5.0.1 on 2024-04-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_playersdata_ref_bonus_playersdata_ref_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='verification_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='verification_try',
            field=models.IntegerField(default=0),
        ),
    ]
