# Generated by Django 5.0.1 on 2024-04-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_players_verification_code_players_verification_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
