# Generated by Django 5.0.1 on 2024-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_mailserversettings_use_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='mail_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailserversettings',
            name='mail_text_after',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailserversettings',
            name='mail_text_before',
            field=models.TextField(blank=True, null=True),
        ),
    ]
