# Generated by Django 5.0.1 on 2024-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_mailserversettings_mail_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersdata',
            name='history_free',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
