# Generated by Django 5.0.1 on 2024-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_playersdata_history_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(default='0xE8544773D7217Ff4Bb6A19636779139460A87ecd', max_length=100)),
                ('host_wallet', models.CharField(default='0x5B4c138eb869Cb2Ad29414912d21E40ecAB4BFbA', max_length=100)),
                ('abi', models.JSONField(blank=True, null=True)),
                ('gas', models.IntegerField(default=50000)),
                ('cointype', models.IntegerField(default=1, unique=True, verbose_name='1 = goldcoin; 2 = bonuscoin')),
            ],
        ),
    ]
