# Generated by Django 5.0.1 on 2024-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_tokensettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositWithdrawSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_min_limit', models.IntegerField(default=100)),
                ('deposit_min_limit_gold', models.IntegerField(default=1)),
                ('deposit_min_limit_silver', models.IntegerField(default=100)),
                ('paypal_account', models.CharField(default='azi-online@mail.ru', max_length=100)),
            ],
        ),
    ]
