# Generated by Django 5.0.1 on 2024-04-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_depositwithdrawsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='gold_transfer_rate',
            field=models.IntegerField(default=100),
        ),
    ]
