# Generated by Django 5.0.1 on 2024-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_depositwithdrawsettings_gold_transfer_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=255, null=True, unique=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='depositwithdrawsettings',
            name='gold_transfer_rate',
            field=models.IntegerField(default=90),
        ),
    ]
