# Generated by Django 5.0.1 on 2024-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_transactionslog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('solved', models.BooleanField(default=False)),
                ('solution', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
