# Generated by Django 5.0.1 on 2024-04-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_transactionserror'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionserror',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
