# Generated by Django 5.0.1 on 2024-05-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_transactionserror_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawsGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateTimeField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_address', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_gold', models.IntegerField(blank=True, null=True)),
                ('amount_token', models.FloatField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_response', models.DateTimeField()),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transactionserror',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
