# Generated by Django 5.0.1 on 2024-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_withdrawsgold_alter_transactionserror_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawsgold',
            name='date_response',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
