# Generated by Django 5.0.1 on 2024-05-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_alter_withdrawsgold_date_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='admin_mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailserversettings',
            name='moderator_mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
