# Generated by Django 5.0.1 on 2024-05-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_mailserversettings_admin_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='paypal_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='paypal_order_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='paypal_token_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionslog',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
