# Generated by Django 5.0.1 on 2024-05-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_depositwithdrawsettings_paypal_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='silver_bnb_rate',
            field=models.IntegerField(default=500000),
        ),
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='silver_usd_rate',
            field=models.IntegerField(default=1000),
        ),
    ]
