# Generated by Django 5.0.1 on 2024-05-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_depositwithdrawsettings_silver_bnb_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositwithdrawsettings',
            name='paypal_merchant_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
