# Generated by Django 5.0.1 on 2024-05-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_paypaltransactionserror_paypaltransactionslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='Player ID number')),
                ('games_silver', models.IntegerField(default=0)),
                ('games_gold', models.IntegerField(default=0)),
                ('games_bonus', models.IntegerField(default=0)),
                ('profit_silver', models.IntegerField(default=0)),
                ('profit_gold', models.IntegerField(default=0)),
                ('profit_bonus', models.IntegerField(default=0)),
                ('relative_silver', models.FloatField(default=0)),
                ('relative_gold', models.FloatField(default=0)),
                ('relative_bonus', models.FloatField(default=0)),
                ('rate', models.FloatField(default=1400)),
                ('games_log', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
