# Generated by Django 5.0.1 on 2024-05-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0039_playersstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersstats',
            name='wins_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playersstats',
            name='wins_gold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playersstats',
            name='wins_silver',
            field=models.FloatField(default=0),
        ),
    ]
