# Generated by Django 5.0.1 on 2024-05-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0040_playersstats_wins_bonus_playersstats_wins_gold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('regular', models.BooleanField(default=False)),
                ('hour', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('cointype', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('to', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
