# Generated by Django 5.0.1 on 2024-05-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0041_airdrops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airdrops',
            old_name='month',
            new_name='day_of_week',
        ),
    ]
