# Generated by Django 5.0.1 on 2024-05-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0042_rename_month_airdrops_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='user_mail_server',
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
    ]
