# Generated by Django 5.0.1 on 2024-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0043_mailserversettings_user_mail_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='google_auth_client_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
