# Generated by Django 5.0.1 on 2024-05-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0044_mailserversettings_google_auth_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='reset_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='reset_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='reset_try',
            field=models.IntegerField(default=0),
        ),
    ]
