# Generated by Django 5.0.1 on 2024-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0045_blacklistip_players_reset_code_players_reset_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='reset_text_after',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailserversettings',
            name='reset_text_before',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='global_reset_try',
            field=models.IntegerField(default=0),
        ),
    ]
