# Generated by Django 5.0.1 on 2024-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0046_mailserversettings_reset_text_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='reset_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
