# Generated by Django 5.0.1 on 2024-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0047_mailserversettings_reset_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreylistIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('reset_try', models.IntegerField(default=0)),
                ('log', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
