# Generated by Django 5.0.1 on 2024-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0048_greylistip'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserversettings',
            name='app_client_url',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
