# Generated by Django 5.0.1 on 2024-04-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azi_online', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailServerSettings',
        ),
    ]
