# Generated by Django 5.0.1 on 2024-02-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Article title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Article subtitle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Article html text')),
                ('publicdate', models.DateTimeField(verbose_name='Publication date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='Image')),
            ],
        ),
    ]
