# Generated by Django 5.0.1 on 2024-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homepagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='article',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='articles',
            field=models.ManyToManyField(to='content.homepagearticles'),
        ),
    ]
