# Generated by Django 5.0.1 on 2024-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_homepagecontent_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearticles',
            name='language',
            field=models.IntegerField(default=1, verbose_name='Language ID (en = 1, ru = 2, sp = 3 ...)'),
            preserve_default=False,
        ),
    ]
