# Generated by Django 5.0.1 on 2024-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_homepagearticles_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagearticles',
            name='language',
            field=models.IntegerField(verbose_name='Language ID'),
        ),
        migrations.DeleteModel(
            name='HomepageContent',
        ),
    ]
