# Generated by Django 5.0.1 on 2024-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_homepagearticles_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutpageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Article title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Article subtitle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Article html text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutarticle_images/', verbose_name='Image')),
                ('language', models.IntegerField(verbose_name='Language ID')),
            ],
        ),
    ]
