# Generated by Django 5.0.1 on 2024-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rulespagearticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportpageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='Article No')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Article title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Article subtitle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Article html text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/support/', verbose_name='Image')),
                ('language', models.IntegerField(verbose_name='Language ID')),
            ],
        ),
        migrations.CreateModel(
            name='TermspageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(unique=True, verbose_name='Article No')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Article title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Article subtitle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Article html text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/terms/', verbose_name='Image')),
                ('language', models.IntegerField(verbose_name='Language ID')),
            ],
        ),
        migrations.CreateModel(
            name='TokenpageArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(unique=True, verbose_name='Article No')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Article title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Article subtitle')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Article html text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/token/', verbose_name='Image')),
                ('language', models.IntegerField(verbose_name='Language ID')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutpagearticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/about/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='homepagearticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/home/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='rulespagearticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/rules/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='rulespagearticles',
            name='step',
            field=models.IntegerField(unique=True, verbose_name='Point of rules'),
        ),
    ]
