# Generated by Django 5.0.1 on 2024-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_supportpagearticle_termspagearticle_tokenpagearticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagearticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/article_images/home/', verbose_name='Image'),
        ),
    ]
