# Generated by Django 5.0.1 on 2024-05-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_homepagearticles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagearticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/home/', verbose_name='Image'),
        ),
    ]
