# Generated by Django 5.0.1 on 2024-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('text_copyright', models.CharField(blank=True, max_length=250, null=True, verbose_name='text_copyright')),
                ('path_facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_facebook')),
                ('path_reddit', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_reddit')),
                ('path_telegram', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_telegram')),
                ('path_x', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_x')),
                ('path_discord', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_discord')),
                ('path_instagram', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_instagram')),
                ('path_appstore', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_appstore')),
                ('path_googleplay', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_googleplay')),
                ('path_support', models.CharField(blank=True, max_length=250, null=True, verbose_name='path_support')),
                ('hint_facebook', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_facebook')),
                ('hint_reddit', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_reddit')),
                ('hint_telegram', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_telegram')),
                ('hint_x', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_x')),
                ('hint_discord', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_discord')),
                ('hint_instagram', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_instagram')),
                ('hint_appstore', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_appstore')),
                ('hint_googleplay', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_googleplay')),
                ('hint_support', models.CharField(blank=True, max_length=250, null=True, verbose_name='hint_support')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('home', models.CharField(max_length=50, verbose_name='home')),
                ('play', models.CharField(max_length=50, verbose_name='play')),
                ('rules', models.CharField(max_length=50, verbose_name='rules')),
                ('top', models.CharField(max_length=50, verbose_name='top')),
                ('about', models.CharField(max_length=50, verbose_name='about')),
                ('table', models.CharField(max_length=50, verbose_name='table')),
                ('signup', models.CharField(max_length=50, verbose_name='singup')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('logout', models.CharField(max_length=50, verbose_name='loguot')),
                ('wallet', models.CharField(max_length=50, verbose_name='wallet')),
                ('disconnect', models.CharField(max_length=50, verbose_name='disconnect')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('english_name', models.CharField(max_length=50, verbose_name='english_name')),
                ('name', models.CharField(max_length=50, verbose_name='name (native name)')),
                ('status', models.BooleanField(verbose_name='status (is available?)')),
            ],
        ),
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('submit', models.CharField(max_length=50, verbose_name='submit')),
                ('login_with', models.CharField(max_length=50, verbose_name='login_with')),
                ('google_hint', models.CharField(max_length=250, verbose_name='google_hint')),
                ('metamask_hint', models.CharField(max_length=250, verbose_name='metamask_hint')),
                ('forgot_password', models.CharField(max_length=100, verbose_name='forgot_password')),
                ('forgot_password_hint', models.CharField(max_length=250, verbose_name='forgot_password_hint')),
                ('modal_title_error', models.CharField(max_length=100, verbose_name='modal_title_error')),
                ('modal_client', models.CharField(max_length=250, verbose_name='modal_client')),
                ('modal_server', models.CharField(max_length=250, verbose_name='modal_server')),
                ('modal_wrong', models.CharField(max_length=250, verbose_name='modal_wrong')),
                ('modal_metamaskerror', models.CharField(max_length=250, verbose_name='modal_metamaskerror')),
                ('modal_button_close', models.CharField(max_length=50, verbose_name='modal_button_close')),
                ('alert_title_congrats', models.CharField(max_length=100, verbose_name='alert_title_congrats')),
                ('alert_successful', models.CharField(max_length=250, verbose_name='alert_successful')),
            ],
        ),
        migrations.CreateModel(
            name='SingupForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('nickname', models.CharField(max_length=100, verbose_name='nickname')),
                ('nickname_hint', models.CharField(max_length=250, verbose_name='nickname_hint')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('email_hint', models.CharField(max_length=250, verbose_name='email_hint')),
                ('ref_code', models.CharField(max_length=50, verbose_name='ref_code')),
                ('ref_code_hint', models.CharField(max_length=250, verbose_name='ref_code_hint')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('repassword', models.CharField(max_length=50, verbose_name='reasswood')),
                ('submit', models.CharField(max_length=50, verbose_name='submit')),
                ('signup_with', models.CharField(max_length=250, verbose_name='singup_with')),
                ('google_hint', models.CharField(max_length=250, verbose_name='google_hint')),
                ('metamask_hint', models.CharField(max_length=50, verbose_name='metamask_hint')),
                ('modal_title_error', models.CharField(max_length=100, verbose_name='modal_title_error')),
                ('modal_client', models.CharField(max_length=250, verbose_name='modal_client')),
                ('modal_server', models.CharField(max_length=250, verbose_name='modal_server')),
                ('modal_nameexist', models.CharField(max_length=250, verbose_name='modal_nameexist')),
                ('modal_nameincorrect', models.CharField(max_length=250, verbose_name='modal_nameincorrect')),
                ('modal_emailexist', models.CharField(max_length=250, verbose_name='modal_emailexist')),
                ('modal_passwordnotmatch', models.CharField(max_length=250, verbose_name='modal_passwordnotmatch')),
                ('modal_passwordshort', models.CharField(max_length=250, verbose_name='modal_passwordshort')),
                ('modal_metamaskerror', models.CharField(max_length=250, verbose_name='modal_metamaskerror')),
                ('modal_button_close', models.CharField(max_length=50, verbose_name='modal_button_close')),
                ('alert_title_congrats', models.CharField(max_length=100, verbose_name='alert_title_congrats')),
                ('alert_successful', models.CharField(max_length=250, verbose_name='alert_successful')),
            ],
        ),
    ]
