# Generated by Django 5.0.1 on 2024-02-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='hint_wallet',
            field=models.CharField(default=1, max_length=250, verbose_name='hint_wallet'),
            preserve_default=False,
        ),
    ]
