# Generated by Django 5.0.1 on 2024-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_header_hint_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
