# Generated by Django 5.0.1 on 2024-02-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_modalerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginform',
            name='alert_successful',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='alert_title_congrats',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='modal_button_close',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='modal_client',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='modal_metamaskerror',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='modal_server',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='modal_title_error',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='modal_wrong',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='alert_successful',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='alert_title_congrats',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_button_close',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_client',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_emailexist',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_metamaskerror',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_nameexist',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_nameincorrect',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_passwordnotmatch',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_passwordshort',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_server',
        ),
        migrations.RemoveField(
            model_name='singupform',
            name='modal_title_error',
        ),
    ]
