# Generated by Django 5.0.1 on 2024-02-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_remove_loginform_alert_successful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginform',
            name='email',
            field=models.CharField(max_length=250, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='login_with',
            field=models.CharField(max_length=250, verbose_name='login_with'),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='singupform',
            name='email',
            field=models.CharField(max_length=250, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='singupform',
            name='metamask_hint',
            field=models.CharField(max_length=250, verbose_name='metamask_hint'),
        ),
    ]
