# Generated by Django 5.0.1 on 2024-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_loginform_email_alter_loginform_login_with_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('form', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
