# Generated by Django 5.0.1 on 2024-02-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='states',
            field=models.TextField(blank=True, null=True),
        ),
    ]
