# Generated by Django 5.0.1 on 2024-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='label')),
                ('form', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
