# Generated by Django 5.0.1 on 2024-02-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_tableshall'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='hall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='hall'),
        ),
    ]
