# Generated by Django 5.0.1 on 2024-04-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_sandboxtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='sandbox',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sandbox'),
        ),
    ]
