# Generated by Django 5.0.1 on 2024-04-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='singupform',
            name='alert_congrats',
            field=models.CharField(default=1, max_length=250, verbose_name='metamask_hint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singupform',
            name='alert_successful',
            field=models.CharField(default=1, max_length=250, verbose_name='metamask_hint'),
            preserve_default=False,
        ),
    ]
