# Generated by Django 5.0.1 on 2024-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_singupform_alert_congrats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singupform',
            name='alert_congrats',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='singupform',
            name='alert_successful',
            field=models.CharField(max_length=250),
        ),
    ]
