# Generated by Django 5.0.1 on 2024-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_toplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='terms',
            field=models.CharField(default=1, max_length=50, verbose_name='about'),
            preserve_default=False,
        ),
    ]
