# Generated by Django 5.0.1 on 2024-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_header_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='terms',
            field=models.CharField(max_length=50, verbose_name='terms'),
        ),
    ]
