# Generated by Django 5.0.1 on 2024-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_alter_header_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='singupform',
            name='privacy_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='singupform',
            name='privacy_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
