# Generated by Django 5.0.1 on 2024-05-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_singupform_privacy_link_singupform_privacy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='singupform',
            name='terms_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
