from django.urls import path
from . import views
from players.views import user_signup, get_users, user_login, user_get_status, user_logout, user_login_google, user_login_metamask, api_get_user_profile_data, api_change_user_nickname, api_change_user_email, api_change_user_phone, api_change_user_country, api_get_user_review_data, api_get_user_history_data, api_create_ref_code, user_confirm_email, user_confirm_code, user_deposit_demo, api_get_token_settings, api_get_payment_settings, user_deposit_gold, user_get_airdrop_coins, user_withdraw_gold, user_deposit_silver_bnb, user_deposit_silver_usdt, user_deposit_silver_paypal, get_payment_settings_silver, api_get_toplist_data, api_get_settings, user_password_reset, user_password_reset_code, user_password_reset_password
from content.views import api_get_homepage_data, api_get_aboutpage_data, api_get_rulespage_data, api_get_termspage_data, api_get_tokenpage_data, api_get_supportpage_data, api_get_privacypolicypage_data

def test():
    print('TEST !!!!!!!!!!!!!!!!!!!!!!!!!!!!!')

urlpatterns = [
    path('get_languages',views.api_get_languages, name='get_languages'),
    path('get_errors',views.api_get_errors, name='get_errors'),
    path('get_header/<int:languageID>',views.api_get_header, name='get_header'),
    path('get_signup_form/<int:languageID>',views.api_get_signup_form, name='get_signup_form'),
    path('get_login_form/<int:languageID>',views.api_get_login_form, name='get_login_form'),
    path('get_footer/<int:languageID>',views.api_get_footer, name='get_footer'),
    path('get_auth_status', user_get_status, name='user_get_status'),
    path('get_user_profile_form', views.api_get_user_profile_form, name='get_user_profile_form'),
    path('get_user_profile_data', api_get_user_profile_data, name='get_user_profile_data'),
    path('change_user_nickname', api_change_user_nickname, name='change_user_nickname'),
    path('change_user_email', api_change_user_email, name='change_user_email'),
    path('change_user_phone', api_change_user_phone, name='change_user_phone'),
    path('change_user_country', api_change_user_country, name='change_user_country'),
    path('create_ref_code', api_create_ref_code, name='create_ref_code'),
    path('get_user_review_form', views.api_get_user_review_form, name='get_user_review_form'),
    path('get_user_review_data/<int:userID>', api_get_user_review_data, name='get_user_review_data'),
    path('get_homepage_form/<int:languageID>', views.api_get_homepage_form, name='get_homepage_form'),
    path('get_homepage_data/<int:languageID>', api_get_homepage_data, name='get_homepage_data'),
    path('get_aboutpage_form/<int:languageID>', views.api_get_aboutpage_form, name='get_aboutpage_form'),
    path('get_aboutpage_data/<int:languageID>', api_get_aboutpage_data, name='get_aboutpage_data'),    
    path('get_rulespage_form/<int:languageID>', views.api_get_rulespage_form, name='get_rulespage_form'),
    path('get_rulespage_data/<int:languageID>', api_get_rulespage_data, name='get_rulespage_data'),
    path('get_termspage_data/<int:languageID>', api_get_termspage_data, name='get_termspage_data'),
    path('get_tokenpage_data/<int:languageID>', api_get_tokenpage_data, name='get_tokenpage_data'),
    path('get_supportpage_data/<int:languageID>', api_get_supportpage_data, name='get_supportpage_data'),
    path('get_privacypolicypage_data/<int:languageID>', api_get_privacypolicypage_data, name='get_privacypolicypage_data'),    
    path('get_tables_interface', views.api_get_tables_interface, name='get_tables_interface'),
    path('get_playtable_interface', views.api_get_playtable_interface, name='get_playtable_interface'),
    path('get_createtable_interface', views.api_get_createtable_interface, name='get_createtable_interface'),
    path('get_accessdenied_interface', views.api_get_accessdenied_interface, name='get_accessdenied_interface'),
    path('get_pagenotfound_interface', views.api_get_pagenotfound_interface, name='get_pagenotfound_interface'),
    path('get_servererror_interface', views.api_get_servererror_interface, name='get_servererror_interface'),
    path('get_sandboxtable_interface', views.api_get_sandboxtable_interface, name='get_sandboxtable_interface'),
    path('user_signup', user_signup, name='user_signup'),
    path('user_login', user_login, name='user_login'),
    path('user_logout', user_logout, name='user_logout'),
    path('get_users', get_users, name='get_users'),
    path('user_login_google', user_login_google, name='user_login_google'),
    path('user_login_metamask', user_login_metamask, name='user_login_metamask'),
    path('get_player_history_interface', views.api_get_user_history_interface, name='get_user_history_interface'),
    path('get_user_history_data', api_get_user_history_data, name='get_user_history_data'),
    path('user_confirm_email', user_confirm_email, name='user_confirm_email'),
    path('user_confirm_code', user_confirm_code, name='user_confirm_code'),
    path('user_deposit_demo', user_deposit_demo, name='user_deposit_demo'),
    path('get_token_settings', api_get_token_settings, name='api_get_token_settings'),
    path('get_payment_settings', api_get_payment_settings, name='api_get_payment_settings'),
    path('user_deposit_gold', user_deposit_gold, name='user_deposit_gold'),
    path('user_get_airdrop_coins', user_get_airdrop_coins, name='user_get_airdrop_coins'),
    path('user_withdraw_gold', user_withdraw_gold, name='user_withdraw_gold'),
    path('user_deposit_silver_bnb', user_deposit_silver_bnb, name='user_deposit_silver_bnb'),
    path('user_deposit_silver_usdt', user_deposit_silver_usdt, name='user_deposit_silver_usdt'),
    path('user_deposit_silver_paypal', user_deposit_silver_paypal, name='user_deposit_silver_paypal'),
    path('get_payment_settings_silver', get_payment_settings_silver, name='get_payment_settings_silver'),
    path('get_toplist_interface', views.api_get_toplist_interface, name='get_toplist_interface'),
    path('get_toplist_data', api_get_toplist_data, name='api_get_toplist_data'),
    path('get_settings', api_get_settings, name='api_get_settings'),
    path('get_recovery_interface', views.api_get_recovery_interface, name='get_recovery_interface'),
    path('user_password_reset', user_password_reset, name='user_password_reset'),
    path('user_password_reset_code', user_password_reset_code, name='user_password_reset_code'),
    path('user_password_reset_password', user_password_reset_password, name='user_password_reset_password'),

]