# Generated by Django 5.0.1 on 2024-02-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Table ID')),
                ('max_players', models.IntegerField(default=6, verbose_name='Table max players')),
                ('drop_suit', models.IntegerField(default=0, verbose_name='Table dropped suit')),
                ('cointype', models.IntegerField(default=1, verbose_name='Table cointype')),
                ('min_bet', models.IntegerField(default=1, verbose_name='Table min bet')),
                ('max_bet', models.IntegerField(default=10, verbose_name='Table max bet')),
                ('table_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Table password')),
                ('players', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('blind_game', models.BooleanField(default=True, verbose_name='Blind game')),
                ('dealing', models.IntegerField(default=1, verbose_name='Table dealer')),
                ('currentgame', models.IntegerField(default=0, verbose_name='Table current game')),
                ('players_now', models.IntegerField(default=0, verbose_name='Table players now')),
                ('sort_index', models.IntegerField(default=0, verbose_name='Table sort index')),
                ('time_stop', models.IntegerField(default=0, verbose_name='Table last activity')),
                ('interval', models.IntegerField(default=30, verbose_name='Table time interval')),
            ],
        ),
    ]
