# Generated by Django 5.0.1 on 2024-03-01 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_game', models.DateTimeField(default=django.utils.timezone.now)),
                ('table_id', models.IntegerField(default=0)),
                ('cointype', models.IntegerField(default=1)),
                ('players', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('min_bet', models.IntegerField(default=1)),
                ('drop_suit', models.IntegerField(default=0)),
                ('trump_suit', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('betting', models.TextField(blank=True, null=True)),
                ('gaming', models.TextField(blank=True, null=True)),
                ('end_game', models.DateTimeField(default=None)),
                ('winner', models.IntegerField(default=0)),
                ('lastgame', models.IntegerField(default=0)),
                ('card_deck', models.CharField(default='1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1', max_length=255)),
                ('card_players', models.CharField(default='0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0', max_length=255)),
                ('card_place1', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('card_place2', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('card_place3', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('card_place', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('cards_now', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('speaker', models.IntegerField(default=0)),
                ('speaker_id', models.IntegerField(default=0)),
                ('stage', models.IntegerField(default=0)),
                ('lastdeal', models.IntegerField(default=1709279204.515648)),
                ('players_bet', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('hodor', models.IntegerField(default=0)),
                ('usersays', models.CharField(default=',,,,,', max_length=255)),
                ('top_bet', models.BooleanField(default=False)),
                ('check_status', models.CharField(default='False, False, False, False, False, False', max_length=255)),
                ('status', models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255)),
                ('turn1win', models.IntegerField(default=0)),
                ('turn2win', models.IntegerField(default=0)),
                ('turn3win', models.IntegerField(default=0)),
                ('current_hodor', models.IntegerField(default=0)),
                ('azi_price', models.IntegerField(default=0)),
            ],
        ),
    ]
