# Generated by Django 5.0.1 on 2024-03-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_game',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='lastdeal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_game',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
