# Generated by Django 5.0.1 on 2024-03-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_end_game_alter_game_lastdeal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cointype',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='usersays',
            field=models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tables',
            name='cointype',
            field=models.IntegerField(default=0, verbose_name='Table cointype'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='dealing',
            field=models.IntegerField(default=0, verbose_name='Table dealer'),
        ),
    ]
