# Generated by Django 5.0.1 on 2024-03-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_cointype_alter_game_usersays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='players_status',
            field=models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255),
        ),
    ]
