# Generated by Django 5.0.1 on 2024-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_tables_players_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='lastdeal',
            field=models.IntegerField(default=0),
        ),
    ]
