# Generated by Django 5.0.1 on 2024-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_tables_lastdeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tables',
            old_name='players_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='tables',
            name='gamestage',
            field=models.IntegerField(default=0, verbose_name='Table dealer'),
        ),
    ]
