# Generated by Django 5.0.1 on 2024-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_rename_players_status_tables_status_tables_gamestage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='usersays_value',
            field=models.CharField(default='0, 0, 0, 0, 0, 0', max_length=255),
        ),
        migrations.AlterField(
            model_name='tables',
            name='gamestage',
            field=models.IntegerField(default=0, verbose_name='Gamestage'),
        ),
    ]
