# Generated by Django 5.0.1 on 2024-03-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_usersays_value_alter_tables_gamestage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='betting',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gaming',
        ),
    ]
