# Generated by Django 5.0.1 on 2024-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_game_betting_remove_game_gaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='betting',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='gaming',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
