# Generated by Django 5.0.1 on 2024-03-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_betting_game_gaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='status',
        ),
    ]
