# Generated by Django 5.0.1 on 2024-03-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_tables_players_remove_tables_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='players',
            field=models.JSONField(default=[0, 0, 0, 0, 0, 0]),
        ),
        migrations.AddField(
            model_name='tables',
            name='status',
            field=models.JSONField(default=[0, 0, 0, 0, 0, 0]),
        ),
    ]
