# Generated by Django 5.0.1 on 2024-03-18 08:42

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_tables_players_tables_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='players',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AlterField(
            model_name='tables',
            name='status',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
    ]
