# Generated by Django 5.0.1 on 2024-03-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_tables_players_alter_tables_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='card_deck',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_place',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_place1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_place2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_place3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cards_now',
        ),
        migrations.RemoveField(
            model_name='game',
            name='check_status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players_bet',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='usersays',
        ),
        migrations.RemoveField(
            model_name='game',
            name='usersays_value',
        ),
    ]
