# Generated by Django 5.0.1 on 2024-03-18 18:32

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_remove_game_card_deck_remove_game_card_place_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='game',
            name='card_place',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='card_place1',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='card_place2',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='card_place3',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='card_players',
            field=models.JSONField(default=games.models.card_players_array),
        ),
        migrations.AddField(
            model_name='game',
            name='cards_now',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='check_status',
            field=models.JSONField(default=games.models.check_players_array),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='players_bet',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='usersays',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
        migrations.AddField(
            model_name='game',
            name='usersays_value',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
    ]
