# Generated by Django 5.0.1 on 2024-03-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_card_deck_game_card_place_game_card_place1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='actual_deck',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
