# Generated by Django 5.0.1 on 2024-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_game_actual_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_hodor',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='hodor',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='speaker',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn1win',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn2win',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn3win',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=-1),
        ),
    ]
