# Generated by Django 5.0.1 on 2024-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_game_current_hodor_alter_game_hodor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='inactive_drop_interval',
            field=models.IntegerField(default=180),
        ),
    ]
