# Generated by Django 5.0.1 on 2024-03-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_tables_inactive_drop_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hodor',
        ),
        migrations.RemoveField(
            model_name='game',
            name='lastdeal',
        ),
        migrations.AddField(
            model_name='game',
            name='log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
