# Generated by Django 5.0.1 on 2024-04-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_remove_game_hodor_remove_game_lastdeal_game_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='default_ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tables',
            name='default_ready_limit',
            field=models.IntegerField(default=3),
        ),
    ]
