# Generated by Django 5.0.1 on 2024-04-01 03:49

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_tables_default_ready_tables_default_ready_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='default_ready',
            field=models.JSONField(default=games.models.default_integer_array),
        ),
    ]
