# Generated by Django 5.0.1 on 2024-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_alter_tables_default_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='inactive_drop_interval',
            field=models.IntegerField(default=300),
        ),
    ]
