# Generated by Django 5.0.1 on 2024-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_alter_tables_inactive_drop_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='sort_index',
        ),
        migrations.AlterField(
            model_name='tables',
            name='interval',
            field=models.IntegerField(default=30, verbose_name='Table interval, sec'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='lastdeal',
            field=models.IntegerField(default=0, verbose_name='Table lastdeal (0 if table inactive)'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Table ID (number)'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='time_stop',
            field=models.IntegerField(default=0, verbose_name='Table time_stop (0 if table active)'),
        ),
    ]
