# Generated by Django 5.0.1 on 2024-04-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_sandboxgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxgame',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
