# Generated by Django 5.0.1 on 2024-04-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_sandboxgame_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxgame',
            name='betting',
        ),
        migrations.RemoveField(
            model_name='sandboxgame',
            name='cointype',
        ),
        migrations.RemoveField(
            model_name='sandboxgame',
            name='gaming',
        ),
        migrations.RemoveField(
            model_name='sandboxgame',
            name='table_id',
        ),
    ]
