# Generated by Django 5.0.1 on 2024-04-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_remove_sandboxgame_betting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SandboxGame',
        ),
    ]
