# Generated by Django 5.0.1 on 2024-04-06 04:07

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_delete_sandboxgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_game', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('max_players', models.IntegerField(default=6)),
                ('players', models.JSONField(default=games.models.default_integer_array)),
                ('min_bet', models.IntegerField(default=1)),
                ('drop_suit', models.IntegerField(default=0)),
                ('trump_suit', models.IntegerField(default=0)),
                ('pot', models.IntegerField(default=0)),
                ('end_game', models.DateTimeField(blank=True, default=None, null=True)),
                ('winner', models.IntegerField(default=-1)),
                ('lastgame', models.IntegerField(default=0)),
                ('actual_deck', models.JSONField(blank=True, default=None, null=True)),
                ('card_players', models.JSONField(default=games.models.card_players_array)),
                ('card_place1', models.JSONField(default=games.models.default_integer_array)),
                ('card_place2', models.JSONField(default=games.models.default_integer_array)),
                ('card_place3', models.JSONField(default=games.models.default_integer_array)),
                ('card_place', models.JSONField(default=games.models.default_integer_array)),
                ('cards_now', models.JSONField(default=games.models.default_integer_array)),
                ('speaker', models.IntegerField(default=-1)),
                ('speaker_id', models.IntegerField(default=0)),
                ('stage', models.IntegerField(default=0)),
                ('players_bet', models.JSONField(default=games.models.default_integer_array)),
                ('usersays', models.JSONField(default=games.models.default_integer_array)),
                ('usersays_value', models.JSONField(default=games.models.default_integer_array)),
                ('top_bet', models.BooleanField(default=False)),
                ('check_status', models.JSONField(default=games.models.check_players_array)),
                ('status', models.JSONField(default=games.models.default_integer_array)),
                ('turn1win', models.IntegerField(default=-1)),
                ('turn2win', models.IntegerField(default=-1)),
                ('turn3win', models.IntegerField(default=-1)),
                ('current_hodor', models.IntegerField(default=-1)),
                ('azi_price', models.IntegerField(default=0)),
                ('blind_game', models.BooleanField(default=True, verbose_name='Blind game')),
                ('dealing', models.IntegerField(default=0, verbose_name='Table dealer')),
            ],
        ),
    ]
