# Generated by Django 5.0.1 on 2024-04-06 14:31

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_sandboxgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxgame',
            name='bot_nicknames',
            field=models.JSONField(default=games.models.nicknames_array),
        ),
    ]
