# Generated by Django 5.0.1 on 2024-04-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_sandboxgame_bot_nicknames'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Bot nickname')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='Bot rating')),
                ('gamemodel', models.IntegerField(blank=True, default=0, null=True, verbose_name='Game model')),
            ],
        ),
    ]
