# Generated by Django 5.0.1 on 2024-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_botplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='botplayers',
            name='democoin',
            field=models.IntegerField(default=100000, verbose_name='Domocoins'),
        ),
    ]
