# Generated by Django 5.0.1 on 2024-04-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_botplayers_democoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='botplayers',
            name='agression',
            field=models.IntegerField(default=50, verbose_name='Greed'),
        ),
        migrations.AddField(
            model_name='botplayers',
            name='blinding',
            field=models.IntegerField(default=50, verbose_name='Greed'),
        ),
        migrations.AddField(
            model_name='botplayers',
            name='bluffing',
            field=models.IntegerField(default=50, verbose_name='Greed'),
        ),
        migrations.AddField(
            model_name='botplayers',
            name='fearless',
            field=models.IntegerField(default=50, verbose_name='Greed'),
        ),
        migrations.AddField(
            model_name='botplayers',
            name='greed',
            field=models.IntegerField(default=50, verbose_name='Greed'),
        ),
        migrations.AddField(
            model_name='botplayers',
            name='risking',
            field=models.IntegerField(default=50, verbose_name='Greed'),
        ),
        migrations.AddField(
            model_name='botplayers',
            name='thrift',
            field=models.IntegerField(default=50, verbose_name='Greed'),
        ),
        migrations.AlterField(
            model_name='botplayers',
            name='democoin',
            field=models.IntegerField(default=100000, verbose_name='Democoins'),
        ),
        migrations.AlterField(
            model_name='sandboxgame',
            name='speaker_id',
            field=models.IntegerField(default=-1),
        ),
    ]
