# Generated by Django 5.0.1 on 2024-04-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_botplayers_agression_botplayers_blinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxgame',
            name='blind_complete',
            field=models.BooleanField(default=False, verbose_name='Blind bet is complete'),
        ),
        migrations.AlterField(
            model_name='botplayers',
            name='agression',
            field=models.IntegerField(default=50, verbose_name='Agression'),
        ),
        migrations.AlterField(
            model_name='botplayers',
            name='blinding',
            field=models.IntegerField(default=50, verbose_name='Blinding'),
        ),
        migrations.AlterField(
            model_name='botplayers',
            name='bluffing',
            field=models.IntegerField(default=50, verbose_name='Bluffing'),
        ),
        migrations.AlterField(
            model_name='botplayers',
            name='fearless',
            field=models.IntegerField(default=50, verbose_name='Fearless'),
        ),
        migrations.AlterField(
            model_name='botplayers',
            name='risking',
            field=models.IntegerField(default=50, verbose_name='Risking'),
        ),
        migrations.AlterField(
            model_name='botplayers',
            name='thrift',
            field=models.IntegerField(default=50, verbose_name='Thrift'),
        ),
    ]
