# Generated by Django 5.0.1 on 2024-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_sandboxgame_blind_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxgame',
            name='gamestage_complete',
            field=models.BooleanField(default=True, verbose_name='Gamestage is complete'),
        ),
    ]
