# Generated by Django 5.0.1 on 2024-04-24 08:11

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_sandboxgame_gamestage_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='botplayers',
            name='deposit_log',
            field=models.JSONField(default=games.models.empty_array),
        ),
    ]
